"""add foreign key to Review

Revision ID: 6dfe1bdfd59a
Revises: f7b736d3ae82
Create Date: 2024-09-16 16:13:53.269535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfe1bdfd59a'
down_revision = 'f7b736d3ae82'
branch_labels = None
depends_on = None


def upgrade():
    # Check if the column already exists
    conn = op.get_bind()
    if not conn.dialect.has_column(conn, 'reviews', 'employee_id'):
        op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
